-- Seed demo: 6 eventos para la seccion Eventos
-- Ejecutar en la base de datos de Valdivia Capital

USE valdiviacapital;

INSERT IGNORE INTO eventos (
    titulo, slug, descripcion, fecha_inicio, fecha_fin, lugar, direccion,
    comuna_id, categoria, imagen_url, url_externo, organizador,
    gratuito, precio, destacado, activo, autor_id
) VALUES
(
    'Festival de Jazz del Calle-Calle 2026',
    'festival-jazz-calle-calle-2026',
    'Tres noches de jazz en vivo con artistas locales e invitados internacionales. Food trucks, feria de vinilos y zona familiar.',
    '2026-06-21 19:30:00',
    '2026-06-21 23:30:00',
    'Parque Saval',
    'Av. Arturo Prat 2200, Valdivia',
    1,
    'Musica',
    'https://picsum.photos/seed/evento-jazz/1200/700',
    'https://valdiviacapital.cl/eventos/jazz-calle-calle',
    'Corporacion Cultural de Valdivia',
    0,
    '$8.000',
    1,
    1,
    1
),
(
    'Feria de Emprendimiento Local en La Union',
    'feria-emprendimiento-local-la-union',
    'Emprendedores de la region exhiben productos de diseno, gastronomia y servicios. Talleres breves y networking.',
    '2026-06-28 10:00:00',
    '2026-06-28 18:30:00',
    'Plaza de La Union',
    'Centro Civico, La Union',
    4,
    'Feria',
    'https://picsum.photos/seed/evento-feria/1200/700',
    'https://valdiviacapital.cl/eventos/feria-emprendimiento',
    'Municipalidad de La Union',
    1,
    NULL,
    0,
    1,
    1
),
(
    'Corrida Familiar Costanera Valdivia 5K',
    'corrida-familiar-costanera-valdivia-5k',
    'Actividad deportiva abierta a todo publico. Incluye categorias infantil, juvenil y adulto. Hidratacion y puntos de asistencia.',
    '2026-07-05 09:00:00',
    '2026-07-05 12:00:00',
    'Costanera de Valdivia',
    'Sector Helipuerto, Valdivia',
    1,
    'Deporte',
    'https://picsum.photos/seed/evento-corrida/1200/700',
    'https://valdiviacapital.cl/eventos/corrida-costanera-5k',
    'IND Los Rios',
    1,
    NULL,
    1,
    1,
    1
),
(
    'Cine Bajo las Estrellas en Panguipulli',
    'cine-bajo-estrellas-panguipulli',
    'Proyeccion gratuita de cine chileno al aire libre. Lleva manta, silla plegable y disfruta una noche de cultura.',
    '2026-07-12 18:30:00',
    '2026-07-12 22:00:00',
    'Playa Grande de Panguipulli',
    'Costanera Panguipulli',
    11,
    'Cultura',
    'https://picsum.photos/seed/evento-cine/1200/700',
    'https://valdiviacapital.cl/eventos/cine-panguipulli',
    'Red de Cultura Los Rios',
    1,
    NULL,
    0,
    1,
    1
),
(
    'Taller de Robótica Escolar en Los Lagos',
    'taller-robotica-escolar-los-lagos',
    'Jornada educativa para estudiantes y docentes con introduccion a programacion, sensores y prototipado basico.',
    '2026-07-19 15:00:00',
    '2026-07-19 19:00:00',
    'Centro Cultural Los Lagos',
    'Balmaceda 450, Los Lagos',
    7,
    'Educacion',
    'https://picsum.photos/seed/evento-robotica/1200/700',
    'https://valdiviacapital.cl/eventos/taller-robotica',
    'Fundacion Futuro Digital',
    0,
    '$3.000',
    0,
    1,
    1
),
(
    'Fiesta Costumbrista de Niebla 2026',
    'fiesta-costumbrista-niebla-2026',
    'Muestras gastronomicas, musica folclorica, artesania y actividades familiares en el borde costero de Niebla.',
    '2026-07-26 11:00:00',
    '2026-07-26 21:30:00',
    'Caleta Niebla',
    'Avenida del Mar, Niebla',
    1,
    'Familiar',
    'https://picsum.photos/seed/evento-costumbrista/1200/700',
    'https://valdiviacapital.cl/eventos/fiesta-niebla',
    'Asociacion de Pescadores de Niebla',
    1,
    NULL,
    1,
    1,
    1
);
